feat: add hetzner
casavo/.github pull request #17
Opened 2023-10-17 14:36 UTC by edubacco

2023-10-17 15:20 UTC, pikachuCa approved these changes

2023-10-17 16:29 UTC, xpepper approved these changes

2023-10-18 07:05 UTC, pferretti requested changes

2023-10-18 07:05 UTC, pferretti commented on radar/casavo-tech-radar.json
> +    "description": "Many parts of the infrastructure (i.e.: CI, monitoring, internal IT tooling, etc...) are build on hetzner virtual machines, as they are cheaper than AWS"
Here I would suggest "hosted" instead of "build" and I would rephrase another part. So:

`Some non-production parts of our infrastructure (i.e.: CI, monitoring, internal IT tooling, etc...) are hosted on Hetzner. The use of Hetzner allows us to reduce and optimise costs.`

2023-10-18 09:40 UTC, pikachuCa commented on radar/casavo-tech-radar.json
> +    "ring": "adopt",
is adopt the right ring ? 

We should put trial no ?

2023-10-18 12:52 UTC, edubacco commented on radar/casavo-tech-radar.json
> +    "ring": "adopt",
Well I've put "adopt" because even if it was not present in the radar, we've been using it for a long time, and I think that we consider it stable and accepted.
We have vital parts of our infrastructure there (i.e.: all the monitoring stack)

2023-10-18 13:15 UTC, moebiusmania approved these changes

2023-10-18 13:35 UTC, pikachuCa commented on radar/casavo-tech-radar.json
> +    "ring": "adopt",
Yes but there is also AWS on adopt.

2023-10-18 13:36 UTC, pikachuCa commented on radar/casavo-tech-radar.json
> +    "ring": "adopt",
They kind are the same no ? 
Or you should make it explicit when to use one or the other.

2023-10-18 13:42 UTC, edubacco commented on radar/casavo-tech-radar.json
> +    "ring": "adopt",
I'm not the right person to answer your question, as I'm not part of the team Infra, and I was not present at the table when they made this choice. What I know is that as AWS costs are ~x10 compared to the hetzner one, we use it "only" for production and client facing workloads, and we try to use hetzner for the rest.

If we want more details, it's better to ask to @giuscri and @pferretti

2023-10-18 14:13 UTC, giuscri approved these changes

2023-10-18 16:05 UTC, pferretti approved these changes

2023-10-18 16:05 UTC, pferretti commented on radar/casavo-tech-radar.json
> +    "ring": "adopt",
That's ok to put Hetzner in adopt, since we have been using it for a while.

I understand your point @pikachuCa , AWS and Hetzner have some overlaps. However, in my opinion it is good that these things also emerge in this Tech Radar: the situation resulting from the tech radar does not have to be perfect. On the contrary, it must be a snapshot of what we have today and a basis for understanding which future optimisation and rationalisation actions can bring value in the future.

2023-10-19 15:29 UTC, xpepper commented on radar/casavo-tech-radar.json
> +    "ring": "adopt",
Even in this case, as we discussed for RabbitMQ vs AWS SQS, what about adding them both?

2023-10-20 08:14 UTC, pikachuCa commented on radar/casavo-tech-radar.json
> +    "ring": "adopt",
ok ok I was a step too far I think. Like to have only one per category and deal with the overlap right now. But yes. let's merge it.

2023-10-20 08:14 UTC, pikachuCa approved these changes

2023-10-23 07:15 UTC, merged