feat: adopt RabbitMQ
casavo/.github pull request #18
Opened 2023-10-17 14:43 UTC by edubacco

2023-10-17 15:20 UTC, pikachuCa commented on radar/casavo-tech-radar.json
>      "description": "We use it for asyncronous messaging"
but not for the event store :) 

We should mention it

2023-10-17 17:43 UTC, xpepper approved these changes

2023-10-18 06:33 UTC, edubacco commented on radar/casavo-tech-radar.json
>      "description": "We use it for asyncronous messaging"
I do not know, maybe in future we will find the time to review that part and we will define how to interact with event store via rabbitmq.
We introduced RabbitMQ years after event store, when all microservices were already interacting with it via http, and we had no reason to change.

What we should not try to do, is to use RabbitMQ as a message broker _and_ an event store. But it's a complex topic and I would not discuss it here.

2023-10-18 07:09 UTC, pferretti requested changes

2023-10-18 07:09 UTC, pferretti commented on radar/casavo-tech-radar.json
>      "description": "We use it for asyncronous messaging"
@edubacco @xpepper I think that it could be worth to add in the description some high level information about why and where we are using RabbitMQ.

2023-10-18 10:00 UTC, pikachuCa commented on radar/casavo-tech-radar.json
> +    "ring": "adopt",
Is it an adopt ?
>For technologies in the adopt ring, we feel strongly that the industry should be adopting these items. We use them where appropriate on our projects; as close to a "no brainer" as possible.

I find AWS SQS pretty nice for asynchronous messaging

2023-10-18 13:16 UTC, moebiusmania approved these changes

2023-10-18 13:21 UTC, edubacco commented on radar/casavo-tech-radar.json
> +    "ring": "adopt",
Actually in our tech radar [readme](https://github.com/casavo/.github/tree/master/radar#rings) we have

> Adopt | Technologies we have high confidence in to serve our purposes. Low risk and recommended to be widely used.

My proposal is to consider RabbitMQ exactly like that: low risk and recommended to be widely used.

For sure there are many good tools for asynchronous messaging other than RabbitMQ, but I think that our choice was already made, and this is not the time to change it and try something different.

@pikachuCa do you think we have specific use cases where RabbitMQ is not a good choice and we need something different?

2023-10-18 13:34 UTC, pikachuCa commented on radar/casavo-tech-radar.json
> +    "ring": "adopt",
The question to answer is : If I (as a engineer at Casavo) need to have some asynchronous messaging then I should use RabbitMQ and not something else ? 
I think the answer is not straightforward. I am not even sure the French services can talk to the current rabbitmq server. And It will require a lot of development (a client in scala for exemple, etc...). So between Aws SQS and RabbitMQ (they both serve the same purpose of async messaging) I am not sure which one is the best...

[We use Aws SQS on French side]

2023-10-18 15:53 UTC, pferretti commented on radar/casavo-tech-radar.json
> +    "ring": "adopt",
@pikachuCa your question is a good one, and I agree with you about the answer.

By now we can add both. After and analysis we can understand if it's possible to drop at least one of them.

2023-10-19 13:31 UTC, edubacco commented on radar/casavo-tech-radar.json
> +    "ring": "adopt",
Ah ok, I didn't know that on french services we're using SQS. I agree on adding them both to correctly represent our actual situation, and then we can understand what to do.

2023-10-19 15:28 UTC, xpepper approved these changes
I would merge this PR and make a new one to add AWS SQS, ok?

2023-10-19 15:48 UTC, pferretti commented
> I would merge this PR and make a new one to add AWS SQS, ok?

I agree

2023-10-20 08:16 UTC, pikachuCa approved these changes

2023-10-23 07:12 UTC, merged